title: Halaman minimal
description: "Tanyalah Aelita."

remote_theme: pmarsceill/just-the-docs
show_downloads: true
search_enabled: false
include: "README.md"

aux_links:
  "Beranda":
    - "/"
    
  "Dokumen":
    - "/docs"

collections:
  docs:
    name: Dokumen
    permalink: "/:collection/:path/"
    output: false

footer_content: "<i>Provided by Muhammad Nabhan Ansarulloh Abyan</i>"
