title: Halaman minimal muhnabhan123
description: "Tanyalah Aelita."

remote_theme: pmarsceill/just-the-docs
show_downloads: true
search_enabled: false
include: "README.md"

aux_links:
  "Situs Blog MNAA":
    - "//imlshorid.github.io"
    
  "/status.amber":
    - "//muhnabhan123.eu.org/status.amber"

collections:
  docs:
    name: Apakah ini?
    permalink: "/:collection/:path/"
    output: true

footer_content: "Provided by Muhammad Nabhan Ansarulloh Abyan"
